spring:
  application:
    name: chap01-rest-api-lecture-source

springdoc:
  packages-to-scan: com.jinosoft.restapi.section05
  # consumers : Swagger? ????? ???? ??? "Content-Type"? ??
  # produces : Swagger? ????? ???? ??? "Content-Type"? ??
  default-consumes-media-type: application/json;charset=UTF-8
  default-produces-media-type: application/json;charset=UTF-8