# prd
spring:
  datasource:
    driver-class-name: org.mariadb.jdbc.Driver
    url: jdbc:mariadb://221.151.189.125:20000/cqrs
    username: swcamp
    password: swcamp

image:
  image-dir: C:/upload/productimgs
  image-url: http://localhost:8080/productimgs/