#Spring Profile
#active? ??? ??? ??
#???? ?? ? application-{active}
spring:
  profiles:
    active: dev

mybatis:
  configuration:
    map-underscore-to-camel-case: true
  mapper-locations: mappers/**/*.xml
  type-aliases-package: com.my.cqrs.product.query.dto

#spring:
#  datasource:
#    driver-class-name: org.mariadb.jdbc.Driver
#    url: jdbc:mariadb://{ip}:{port}/{db-name}
#    username: {user}
#    password: {pwd}
#
#image:
#  image-dir: {??? ?? ?? ??}
#  image-url: {??? ?? ?? URL}